---
title: "<br><br>Examples of Past Work"
output: html_document
---

&nbsp;

&nbsp;

#### **Poster: Climate variation and under-5 acute malnutrition in Bangladesh** **([PDF](./files/poster.pdf))**
Working with [Dr. Hannah Nissan](http://www.lse.ac.uk/GranthamInstitute/profile/hannah-nissan/), I performed preliminary analyses on links between climate events and child anthropometry at multiple timescales. Our [research poster](./files/poster.pdf) won first prize at the 2020 NYC [Clinical Climate Change Conference](https://clinicalclimatechange.com/2020).

&nbsp;

#### **Project: Evictions in Brooklyn** **([Site](https://simmwill.github.io/evictions))**
Evictions represent a major source of housing instability in the United States, especially in vulnerable communities. Eviction has now grown to what many consider epidemic proportions, with over 450,000 evictions filed in New York City between 2013 and 2015.

As a team of collaborators in Columbia's [Data Science I](https://p8105.com) course, we investigated what neighborhood-level factors could be used to predict yearly eviction rates in Brooklyn. We used data from Priceton's [Eviction Lab](https://evictionlab.org), the [US Census Database](https://factfinder.census.gov/faces/nav/jsf/pages/guided_search.xhtml), and [NYC Open Data](https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-nynta.page).

We created a [webpage](https://simmwill.github.io/evictions), complete with analysis details and an interactive [prediction tool](https://willsimmons.shinyapps.io/model_building/) I made in Shiny.

&nbsp;

For info on my current research or to see my CV, click [here](https://simmwill.github.io/cv).

&nbsp;

More examples coming soon.

&nbsp;
&nbsp;